### ISSUE TITLE
bootstrap 3 examples doesn't work

### ISSUE THREAD

**Issue by Aurimas86** [t0m/select2-bootstrap-css#64]
All examples at https://fk.github.io/select2-bootstrap-css/index.html don't do anything as they cannot find select2.js and select2.css files.

**Comment by fk** [comment]
Thanks for reporting this @Aurimas86.

Turns out Select2 moved its demo pages from https://ivaynberg.github.io/select2/ to https://select2.github.io/ while they're preparing for Select2 4.0 (which is currently in beta); the example page still pulls files from the old location.

I have some minutes right now and will see if there's an easy fix.

**Comment by fk** [comment]
Fixed!
:+1:
